pool:
  name: Default
  demands:
    - agent.name -equals MyDevAgent1

trigger:
  - main

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'
    includePreviewVersions: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Project'

- script: dotnet pack --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishVstsFeed: 'YOUR_FEED_ID'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
